<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Book;

class BooksSeeder extends Seeder
{
    public function run(): void
    {
        $libros = [
            [
                'titulo' => 'Cien Años de Soledad',
                'descripcion' => 'Una obra cumbre de la literatura latinoamericana que relata la historia de la familia Buendía en el mítico pueblo de Macondo.',
                'autor' => 'Gabriel García Márquez',
                'año' => 1967,
                'isbn' => '9780307474728',
                'imagen' => '',
                'categories'=> [1],

            ],
            [
                'titulo' => 'La Vorágine',
                'descripcion' => 'Un clásico colombiano que denuncia los abusos en la explotación del caucho en la selva amazónica.',
                'autor' => 'José Eustasio Rivera',
                'año' => 1924,
                'isbn' => '9789583000170',
                'categories'=> [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Amor en los Tiempos del Cólera',
                'descripcion' => 'Una historia de amor eterno que explora la pasión, el tiempo y la fidelidad a través de los años.',
                'autor' => 'Gabriel García Márquez',
                'año' => 1985,
                'isbn' => '9780307389732',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Pedro Páramo',
                'descripcion' => 'Un viaje onírico y poético al pueblo de Comala en busca del padre perdido, en medio de voces del más allá.',
                'autor' => 'Juan Rulfo',
                'año' => 1955,
                'isbn' => '9788437604947',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Rayuela',
                'descripcion' => 'Una novela experimental que desafía la lectura lineal, símbolo del boom latinoamericano.',
                'autor' => 'Julio Cortázar',
                'año' => 1963,
                'isbn' => '9788437602288',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Santa',
                'descripcion' => 'Una cruda historia de redención y tragedia sobre una joven mexicana en situación de prostitución.',
                'autor' => 'Federico Gamboa',
                'año' => 1903,
                'isbn' => '9789682314344',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Detectives Salvajes',
                'descripcion' => 'Un mosaico narrativo que sigue las huellas de dos poetas desaparecidos en un viaje por la literatura y la identidad latinoamericana.',
                'autor' => 'Roberto Bolaño',
                'año' => 1998,
                'isbn' => '9788433973979',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Del Amor y Otros Demonios',
                'descripcion' => 'Un amor imposible en medio de supersticiones, religión y locura en la época colonial.',
                'autor' => 'Gabriel García Márquez',
                'año' => 1994,
                'isbn' => '9780307387264',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Novelas Cortas',
                'descripcion' => 'Compilación de relatos breves que retratan la sociedad española del siglo XIX con aguda crítica y humor.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1881,
                'isbn' => '',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'El capitán veneno',
                'descripcion' => 'Una historia romántica y satírica sobre un militar herido que descubre el poder transformador del amor.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1881,
                'isbn' => '9788467023217',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'El clavo',
                'descripcion' => 'Un misterioso crimen y una carta olvidada desencadenan esta intriga de amor y justicia ambientada en la España del XIX.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1853,
                'isbn' => '9781533210932',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Niño de la Bola',
                'descripcion' => 'Un relato romántico de pasiones, venganzas y nobleza en la Andalucía del siglo XIX.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1880,
                'isbn' => '9788498970853',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'El sombrero de tres picos',
                'descripcion' => 'Una divertida sátira sobre los enredos amorosos entre una pareja humilde y un corregidor celoso.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1874,
                'isbn' => '9788420411647',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Regenta',
                'descripcion' => 'Una de las grandes novelas realistas españolas, que retrata el conflicto interno de una mujer atrapada en la hipocresía social.',
                'autor' => 'Leopoldo Alas',
                'año' => 1884,
                'isbn' => '9788420674110',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Su único hijo',
                'descripcion' => 'Tragedia íntima sobre maternidad frustrada y decadencia moral en la pequeña burguesía española.',
                'autor' => 'Leopoldo Alas',
                'año' => 1890,
                'isbn' => '9788420674127',
                'categories' => [1, 11],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Navidad en las Montañas',
                'descripcion' => 'Un mensaje esperanzador sobre la fraternidad humana, la fe y el amor al prójimo en tiempos difíciles.',
                'autor' => 'Ignacio Manuel Altamirano',
                'año' => 1871,
                'isbn' => '9789682315635',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Adán y Eva en el paraíso',
                'descripcion' => 'Una sátira romántica que recrea el primer amor con ironía en un paraíso moderno lleno de contradicciones.',
                'autor' => 'Eça de Queirós',
                'año' => 1895,
                'isbn' => '9786070302437',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Vida De Lazarillo De Tormes Y De Sus Fortunas',
                'descripcion' => 'Obra fundacional de la novela picaresca española que narra la astucia de un joven pobre para sobrevivir.',
                'autor' => 'Anonimo',
                'año' => 1554,
                'isbn' => '9788420430457',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'La metamorfosis, o, El asno de oro',
                'descripcion' => 'Una fábula mágica sobre la transformación de un hombre en asno, cargada de humor, crítica y misterio.',
                'autor' => 'Apuleius',
                'año' => 160,
                'isbn' => '9788420650565',
                'categories' => [5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los caciques',
                'descripcion' => 'Comedia teatral que critica la corrupción política local en clave humorística y costumbrista.',
                'autor' => 'Carlos Arniches y Barrera',
                'año' => 1913,
                'isbn' => '9788437623966',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Un paseo por Paris, retratos al natural',
                'descripcion' => 'Crónica viajera que retrata la vida parisina con observación social y sentido irónico.',
                'autor' => 'Roque Barcia',
                'año' => 1865,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'El amor, el dandysmo y la intriga',
                'descripcion' => 'Una historia de amores imposibles, apariencias y engaños en la alta sociedad del siglo XIX.',
                'autor' => 'Pío Baroja',
                'año' => 1943,
                'isbn' => '9788490745244',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'El aprendiz de conspirador',
                'descripcion' => 'Novela política con tintes de aventura que sigue a un joven enredado en planes revolucionarios.',
                'autor' => 'Pío Baroja',
                'año' => 1935,
                'isbn' => '9788490745251',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'El árbol de la ciencia',
                'descripcion' => 'Una reflexión existencialista sobre el conocimiento, la muerte y el sentido de la vida en la España moderna.',
                'autor' => 'Pío Baroja',
                'año' => 1911,
                'isbn' => '9788420674172',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Caminos del Mundo',
                'descripcion' => 'Una travesía por distintas ciudades de Europa que enfrenta al protagonista con dilemas morales y políticos.',
                'autor' => 'Pío Baroja',
                'año' => 1924,
                'isbn' => '9788490745268',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Caudillos de 1830',
                'descripcion' => 'Crónica novelada sobre los movimientos revolucionarios en la Europa del siglo XIX.',
                'autor' => 'Pío Baroja',
                'año' => 1931,
                'isbn' => '9788490745275',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Contrastes de la Vida',
                'descripcion' => 'Novela que examina las diferencias sociales, espirituales y morales de la España contemporánea.',
                'autor' => 'Pío Baroja',
                'año' => 1904,
                'isbn' => '',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'La dama errante',
                'descripcion' => 'Relato de una mujer independiente que desafía las convenciones sociales mientras busca su destino.',
                'autor' => 'Pío Baroja',
                'año' => 1908,
                'isbn' => '9788420674189',
                'categories' => [1, 9],
                'imagen' => '',
            ],            
            [
                'titulo' => 'El Escuadrón del Brigante',
                'descripcion' => 'Una novela de aventuras con tintes de conspiración, donde la acción y la intriga dominan cada página.',
                'autor' => 'Pío Baroja',
                'año' => 1922,
                'isbn' => '9788490745282',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'Las figuras de cera',
                'descripcion' => 'Una oscura narración donde la muerte, el engaño y los dobles sentidos se entrelazan en un entorno casi gótico.',
                'autor' => 'Pío Baroja',
                'año' => 1925,
                'isbn' => '9788490745299',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'Las Furias',
                'descripcion' => 'Un retrato pasional y desencantado de la lucha interna entre el amor, el poder y los deseos destructivos.',
                'autor' => 'Pío Baroja',
                'año' => 1929,
                'isbn' => '9788490745305',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Las inquietudes de Shanti Andia',
                'descripcion' => 'Aventura y melancolía se combinan en el relato de un joven marino que busca su destino entre misterios del pasado.',
                'autor' => 'Pío Baroja',
                'año' => 1911,
                'isbn' => '9788420674196',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Isabelina',
                'descripcion' => 'Una novela política ambientada en la convulsa España del siglo XIX, donde los ideales chocan con la realidad.',
                'autor' => 'Pío Baroja',
                'año' => 1930,
                'isbn' => '9788490745312',
                'categories' => [1, 12],
                'imagen' => '',
            ],
            [
                'titulo' => 'La lucha por la vida: Aurora roja',
                'descripcion' => 'Crónica de la vida obrera madrileña que muestra la crudeza del trabajo, la pobreza y la lucha de clases.',
                'autor' => 'Pío Baroja',
                'año' => 1905,
                'isbn' => '9788420674202',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La lucha por la vida: La busca',
                'descripcion' => 'Un joven llega a Madrid y enfrenta la marginación, el hambre y la miseria en esta cruda novela realista.',
                'autor' => 'Pío Baroja',
                'año' => 1904,
                'isbn' => '9788420674219',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'La lucha por la vida: Mala hierba',
                'descripcion' => 'Continuación de “La busca”, que retrata cómo la delincuencia y la lucha por sobrevivir modelan al protagonista.',
                'autor' => 'Pío Baroja',
                'año' => 1904,
                'isbn' => '9788420674226',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Mala Hierba',
                'descripcion' => 'Segunda parte de la trilogía "La lucha por la vida", marcada por el crecimiento del protagonista en ambientes hostiles.',
                'autor' => 'Pío Baroja',
                'año' => 1904,
                'isbn' => '9788420674226',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'La nave de los locos',
                'descripcion' => 'Una sátira filosófica con personajes errantes que encarnan la locura social, moral y política.',
                'autor' => 'Pío Baroja',
                'año' => 1925,
                'isbn' => '',
                'categories' => [1, 12],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Recursos de la Astucia',
                'descripcion' => 'Un relato lleno de giros donde el ingenio y la estrategia se convierten en herramientas para sobrevivir.',
                'autor' => 'Pío Baroja',
                'año' => 1924,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Ruta del Aventurero',
                'descripcion' => 'Viajes, encuentros y desafíos forman parte de esta travesía cargada de aventuras y reflexiones sobre la libertad.',
                'autor' => 'Pío Baroja',
                'año' => 1936,
                'isbn' => '',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Sabor de la Venganza',
                'descripcion' => 'Una novela intensa que explora las consecuencias emocionales y sociales del deseo de venganza.',
                'autor' => 'Pío Baroja',
                'año' => 1941,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Veleta de Gastizar',
                'descripcion' => 'Crónica familiar y política ambientada en el País Vasco, con fuertes tensiones ideológicas.',
                'autor' => 'Pío Baroja',
                'año' => 1935,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Zalacaín El Aventurero',
                'descripcion' => 'Un clásico de la novela de aventuras donde se retrata el valor, la astucia y el espíritu libre del protagonista.',
                'autor' => 'Pío Baroja',
                'año' => 1909,
                'isbn' => '9788420674233',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 1/9',
                'descripcion' => 'Primera entrega de esta intensa serie sobre conspiraciones religiosas, amor y secretos de poder.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 2/9',
                'descripcion' => 'La intriga se intensifica con nuevos personajes y conflictos en esta saga crítica de la iglesia y la política.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 3/9',
                'descripcion' => 'Se profundiza el drama familiar y el enfrentamiento entre fe, ambición y deseo en esta tercera parte.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 4/9',
                'descripcion' => 'La historia avanza con revelaciones y traiciones que ponen a prueba la lealtad de los protagonistas.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 5/9',
                'descripcion' => 'Un capítulo de tensión creciente donde las fuerzas oscuras detrás del poder eclesiástico se hacen más evidentes.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],            
            [
                'titulo' => 'La araña negra, parte 6/9',
                'descripcion' => 'Los secretos del poder eclesiástico se vuelven más oscuros en esta sexta entrega llena de tensión y conspiraciones.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 7/9',
                'descripcion' => 'Una trama envolvente donde el fanatismo, la traición y el poder alcanzan su punto más álgido.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 8/9',
                'descripcion' => 'Penúltimo episodio en el que los conflictos internos y políticos se intensifican rumbo al desenlace.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La araña negra, parte 9/9',
                'descripcion' => 'El gran cierre de una serie polémica y poderosa que cuestiona las estructuras religiosas y sociales.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'Arroz y tartana',
                'descripcion' => 'Retrato satírico de la alta sociedad valenciana y los conflictos familiares motivados por la ambición.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1894,
                'isbn' => '9788499535747',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Barraca',
                'descripcion' => 'Novela social sobre los abusos hacia los campesinos en la huerta valenciana y sus luchas por justicia.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1898,
                'isbn' => '9788490743189',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Bodega',
                'descripcion' => 'Crítica social sobre la explotación obrera en el mundo vinícola andaluz, teñida de drama y denuncia.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1905,
                'isbn' => '9788423912264',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cañas y Barro',
                'descripcion' => 'Una de las obras más representativas del naturalismo español, que retrata la lucha entre tradición y progreso.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1902,
                'isbn' => '9788497407169',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Catedral',
                'descripcion' => 'Reflexión crítica sobre la hipocresía religiosa y el conflicto entre fe, poder y conciencia obrera.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1903,
                'isbn' => '9788499531633',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Cuatro Jinetes del Apocalipsis',
                'descripcion' => 'Una épica familiar que retrata los horrores de la Primera Guerra Mundial desde una perspectiva humana.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1916,
                'isbn' => '9788497406506',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los enemigos de la mujer',
                'descripcion' => 'Crítica a las relaciones de poder entre géneros, donde la seducción y la ambición chocan con la moral.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1916,
                'isbn' => '9788499532661',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Entre naranjos',
                'descripcion' => 'Amor y política en la Valencia de principios del siglo XX, donde el deber y la pasión entran en conflicto.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1900,
                'isbn' => '9788497406513',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La familia del doctor Pedraza',
                'descripcion' => 'Historia íntima con tintes sentimentales que refleja los valores sociales de su época.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1903,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Flor de mayo',
                'descripcion' => 'Una historia sencilla pero poderosa sobre el amor, la vida sencilla y los conflictos sociales.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1895,
                'isbn' => '9788499532647',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La horda',
                'descripcion' => 'Retrato de la clase trabajadora urbana y sus luchas en un entorno dominado por la desigualdad.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1905,
                'isbn' => '9788499532654',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'El intruso',
                'descripcion' => 'Intriga y tensiones ideológicas entre obreros y burgueses en una novela intensa y política.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1904,
                'isbn' => '9788499532678',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'La maja desnuda',
                'descripcion' => 'Amor, arte y deseo en esta novela inspirada en la pintura y el escándalo de la época.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1906,
                'isbn' => '9788499532685',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Mare nostrum',
                'descripcion' => 'Una novela marítima y patriótica ambientada durante la Gran Guerra, llena de aventuras y reflexión.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1918,
                'isbn' => '9788497406537',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los muertos mandan',
                'descripcion' => 'Relato dramático sobre el peso de las apariencias, el pasado y las imposiciones sociales.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1909,
                'isbn' => '9788499532692',
                'categories' => [1, 10],
                'imagen' => '',
            ],
            [
                'titulo' => 'Novelas de la Costa Azul',
                'descripcion' => 'Un conjunto de relatos ambientados en el Mediterráneo, donde el lujo y la pasión se entrelazan.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1926,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],            
            [
                'titulo' => 'El papa del mar',
                'descripcion' => 'Novela histórica que retrata las luchas de poder y fe en tiempos de la Inquisición en Valencia.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1925,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'El paraiso de las mujeres',
                'descripcion' => 'Una sátira social sobre el rol femenino y el contraste entre civilizaciones modernas y primitivas.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1922,
                'isbn' => '',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'El préstamo de la difunta',
                'descripcion' => 'Una historia de amor y misterio donde una herencia inesperada desata intrigas familiares.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1900,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La reina Calafia',
                'descripcion' => 'Inspirada en la mítica reina de California, esta novela combina aventura, exotismo y crítica social.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1924,
                'isbn' => '',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Sangre y arena',
                'descripcion' => 'Una intensa historia sobre el amor, la fama y la tragedia de un torero en la España taurina.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1908,
                'isbn' => '9788497406520',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'Sónnica la cortesana',
                'descripcion' => 'Novela ambientada en la antigua Grecia que entrelaza el amor con la lucha por la libertad.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1901,
                'isbn' => '9788497406550',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Tierra de Todos',
                'descripcion' => 'Una reflexión literaria sobre el progreso, el nacionalismo y la convivencia de culturas.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1922,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La vuelta al mundo de un novelista; vol. 1/3',
                'descripcion' => 'Primera parte del relato de viajes de Blasco Ibáñez, donde explora culturas con mirada crítica y apasionada.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1924,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La vuelta al mundo de un novelista; vol. 2/3',
                'descripcion' => 'Segunda entrega del diario de viajes del autor, repleta de observaciones políticas y sociales.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1924,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La vuelta al mundo de un novelista; vol. 3/3',
                'descripcion' => 'Tercera y última parte del viaje literario de Blasco Ibáñez por Oriente y América.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1924,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Fernando IV de Castilla, o, Dos muertes a un tiempo',
                'descripcion' => 'Relato histórico que dramatiza los conflictos del rey niño y los enigmas de su trágica muerte.',
                'autor' => 'África Bolangero',
                'año' => 1855,
                'isbn' => '',
                'categories' => [1, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Doña Perfecta',
                'descripcion' => 'Crítica feroz al fanatismo y la intolerancia en la España del siglo XIX, a través de un drama familiar.',
                'autor' => 'Benito Pérez Galdós',
                'año' => 1876,
                'isbn' => '9788420665729',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Clemencia',
                'descripcion' => 'Primera novela mexicana moderna, que combina romance y patriotismo en tiempos convulsos.',
                'autor' => 'Fernán Caballero',
                'año' => 1852,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La gaviota',
                'descripcion' => 'Una historia costumbrista que exalta el folclor andaluz y los valores tradicionales.',
                'autor' => 'Fernán Caballero',
                'año' => 1849,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La isla del tesoro',
                'descripcion' => 'Clásico de aventuras que marcó la narrativa pirata, lleno de acción, mapas y tesoros escondidos.',
                'autor' => 'Robert Louis Stevenson',
                'año' => 1883,
                'isbn' => '9788423918013',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cartas de mi molino',
                'descripcion' => 'Relatos breves impregnados de nostalgia, ternura y observación de la vida rural provenzal.',
                'autor' => 'Alphonse Daudet',
                'año' => 1866,
                'isbn' => '9788437607379',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Amar es vencer',
                'descripcion' => 'Una novela moralista donde el sacrificio y la bondad se imponen frente a la adversidad.',
                'autor' => 'Pauline Caro',
                'año' => 1862,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'El criticón (tomo 1 de 2)',
                'descripcion' => 'Primera parte de esta obra filosófica y satírica que representa la vida como una constante lucha interior.',
                'autor' => 'Baltasar Gracián y Morales',
                'año' => 1651,
                'isbn' => '9788420636996',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'El criticón (tomo 2 de 2)',
                'descripcion' => 'Conclusión de la alegoría de la existencia humana, escrita con agudeza barroca y reflexión profunda.',
                'autor' => 'Baltasar Gracián y Morales',
                'año' => 1657,
                'isbn' => '9788420636996',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Don Quijote',
                'descripcion' => 'La obra cumbre de la literatura española que satiriza los libros de caballería con profundidad filosófica y humor.',
                'autor' => 'Miguel de Cervantes Saavedra',
                'año' => 1605,
                'isbn' => '9788420687004',
                'categories' => [1],
                'imagen' => '',
            ],            
            [
                'titulo' => 'La vida en los campos',
                'descripcion' => 'Retrato realista de la vida rural siciliana, donde la miseria y la tradición marcan el destino de sus personajes.',
                'autor' => 'Giovanni Verga',
                'año' => 1880,
                'isbn' => '9788437608536',
                'categories' => [1],
                'imagen' => '',
            ],
            [
                'titulo' => 'Germana',
                'descripcion' => 'Una joven y su lucha entre la pasión y los valores sociales en un relato romántico francés del siglo XIX.',
                'autor' => 'Edmond About',
                'año' => 1857,
                'isbn' => '',
                'categories' => [1, 9],
                'imagen' => '',
            ],
            [
                'titulo' => 'La copa de Verlaine',
                'descripcion' => 'Poesía modernista influenciada por la bohemia y la melancolía del simbolismo francés.',
                'autor' => 'Emilio Carrere',
                'año' => 1914,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cosas nuevas y viejas',
                'descripcion' => 'Recopilación de textos sobre costumbres y hechos históricos andaluces con mirada crítica.',
                'autor' => 'Manuel Chaves Rey',
                'año' => 1915,
                'isbn' => '',
                'categories' => [6, 4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Manfredo',
                'descripcion' => 'Dramática obra poética sobre el tormento interior de un hombre perseguido por su pasado.',
                'autor' => 'George Gordon Byron',
                'año' => 1817,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Rafael Cordero: Elogio Póstumo',
                'descripcion' => 'Homenaje a un educador afrodescendiente que luchó por la alfabetización en Puerto Rico.',
                'autor' => 'Salvador Brau',
                'año' => 1890,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Edipo rey; Edipo en Colona; Antígona',
                'descripcion' => 'Trilogía clásica que explora el destino, la culpa y la justicia en la mitología griega.',
                'autor' => 'Sófocles',
                'año' => -400,
                'isbn' => '9788437601063',
                'categories' => [3, 5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Oriente',
                'descripcion' => 'Relatos de viaje con tintes exóticos, donde el autor observa y juzga culturas ajenas a Europa.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1924,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'El libro de las mil y una noche',
                'descripcion' => 'Colección de relatos árabes cargados de magia, sabiduría y relatos dentro de relatos.',
                'autor' => 'Anonimo',
                'año' => 800,
                'isbn' => '9788420686684',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'Deberes de buena sociedad',
                'descripcion' => 'Manual sobre normas sociales y etiqueta en la vida burguesa del siglo XIX.',
                'autor' => 'Camilo Fabra',
                'año' => 1892,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Tres Comedias Modernas',
                'descripcion' => 'Obras teatrales cómicas que reflejan la vida cotidiana con humor y crítica social.',
                'autor' => 'Ramos Carrión',
                'año' => 1890,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La nariz de un notario',
                'descripcion' => 'Sátira que combina elementos de lo absurdo y lo grotesco con una crítica a la hipocresía social.',
                'autor' => 'Edmond About',
                'año' => 1862,
                'isbn' => '',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Merodeadores de Fronteras',
                'descripcion' => 'Aventuras en territorios indómitos donde el honor y la supervivencia se enfrentan.',
                'autor' => 'Gustave Aimard',
                'año' => 1864,
                'isbn' => '',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Las noches mejicanas',
                'descripcion' => 'Cuentos ambientados en el México del siglo XIX, donde lo salvaje y lo humano se entrelazan.',
                'autor' => 'Gustave Aimard',
                'año' => 1863,
                'isbn' => '',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cosas que fueron: Cuadros de costumbres',
                'descripcion' => 'Reflexiones costumbristas sobre la España rural y urbana con agudo sentido del humor.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1871,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'El tratado de la pintura',
                'descripcion' => 'Reflexión teórica y artística de Leonardo sobre las bases del arte pictórico del Renacimiento.',
                'autor' => 'Leonardo da Vinci',
                'año' => 1651,
                'isbn' => '9788477741650',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Doña Clarines y Mañana de Sol',
                'descripcion' => 'Dos comedias breves llenas de gracia popular andaluza y fina observación de la vida cotidiana.',
                'autor' => 'Álvarez Quintero',
                'año' => 1909,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Máximas Morales en Ilocano y Castellano',
                'descripcion' => 'Sentencias éticas bilingües que buscan orientar el comportamiento en la vida cotidiana.',
                'autor' => 'Anonimo',
                'año' => 1889,
                'isbn' => '',
                'categories' => [8],
                'imagen' => '',
            ],
            [
                'titulo' => 'Almacen de recetas escogidas y probadas',
                'descripcion' => 'Compendio práctico de cocina tradicional, con fórmulas sencillas y sabrosas.',
                'autor' => 'Anonimo',
                'año' => 1898,
                'isbn' => '',
                'categories' => [7],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cocina moderna',
                'descripcion' => 'Recetario adaptado al siglo XX, con propuestas variadas para el hogar latinoamericano.',
                'autor' => 'Anonimo',
                'año' => 1910,
                'isbn' => '',
                'categories' => [7],
                'imagen' => '',
            ],            
            [
                'titulo' => 'La Igualdad Social y Política y sus Relaciones con la Libertad',
                'descripcion' => 'Ensayo pionero sobre justicia social, derechos y libertad, escrito con perspectiva crítica y humanista.',
                'autor' => 'Concepción Arenal',
                'año' => 1870,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Granos de oro: Pensamientos Seleccionados en las Obras de José Martí',
                'descripcion' => 'Compilación de frases inspiradoras que resumen el pensamiento político y ético del héroe cubano.',
                'autor' => 'José Martí',
                'año' => 1890,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Comedias, tomo 1 de 3 : Los Acarnienses, los Caballeros, las Nubes',
                'descripcion' => 'Primer volumen de comedias clásicas griegas con crítica política, sátira social y humor agudo.',
                'autor' => 'Aristophanes',
                'año' => -425,
                'isbn' => '9788437600042',
                'categories' => [3, 5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Comedias, tomo 2 de 3 : Las Avispas, la Paz, las Aves, Lisístrata',
                'descripcion' => 'Segundo tomo que incluye la famosa "Lisístrata", ejemplo de humor y resistencia femenina en la comedia clásica.',
                'autor' => 'Aristophanes',
                'año' => -421,
                'isbn' => '',
                'categories' => [3, 5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Comedias, tomo 3 de 3 : Las Fiestas de Ceres, las Ranas, las Junteras, Pluto',
                'descripcion' => 'Último volumen de sátiras atenienses que combinan fantasía, crítica y mitología con ingenio brillante.',
                'autor' => 'Aristophanes',
                'año' => -405,
                'isbn' => '',
                'categories' => [3, 5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Es mi hombre: Tragedia grotesca en tres actos',
                'descripcion' => 'Una sátira popular sobre la vida de barrio con humor absurdo y personajes entrañables.',
                'autor' => 'Carlos Arniches y Barrera',
                'año' => 1921,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Sainetes',
                'descripcion' => 'Pequeñas piezas cómicas que retratan costumbres españolas con humor ligero y crítica social.',
                'autor' => 'Carlos Arniches y Barrera',
                'año' => 1910,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La señorita de Trevelez: Farsa cómica en tres actos',
                'descripcion' => 'Farsa dramática que denuncia el desprecio social y la crueldad disfrazada de broma.',
                'autor' => 'Carlos Arniches y Barrera',
                'año' => 1916,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los valores literarios',
                'descripcion' => 'Reflexiones críticas sobre la literatura y el lenguaje por una de las voces clave del noventayochismo.',
                'autor' => 'Azorín',
                'año' => 1913,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Criterio',
                'descripcion' => 'Obra fundamental del pensamiento católico que propone principios filosóficos para la vida práctica.',
                'autor' => 'Jaime Luciano Balmes',
                'año' => 1845,
                'isbn' => '9788430924381',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Filosofía Fundamental, Tomo I',
                'descripcion' => 'Inicio del ambicioso tratado de Balmes sobre el conocimiento, la fe y la razón.',
                'autor' => 'Jaime Luciano Balmes',
                'año' => 1846,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Filosofía Fundamental, Tomo II',
                'descripcion' => 'Desarrollo de las bases filosóficas para un pensamiento católico moderno.',
                'autor' => 'Jaime Luciano Balmes',
                'año' => 1846,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Filosofía Fundamental, Tomo III',
                'descripcion' => 'Exploración profunda de la lógica y la metafísica desde una mirada cristiana.',
                'autor' => 'Jaime Luciano Balmes',
                'año' => 1846,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Filosofía Fundamental, Tomo IV',
                'descripcion' => 'Cierre del tratado con reflexiones sobre el alma, el bien y la verdad universal.',
                'autor' => 'Jaime Luciano Balmes',
                'año' => 1846,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Crónicas de Marianela',
                'descripcion' => 'Narración sobre la vida de la heroína galdosiana desde una óptica complementaria y nostálgica.',
                'autor' => 'Angélica Palma',
                'año' => 1916,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'El aceite de olivas',
                'descripcion' => 'Ensayo contemporáneo que conecta historia, agricultura y tradición mediterránea.',
                'autor' => 'Alejandro Bizzarri',
                'año' => 1998,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Moral social : apreciación de Hostos',
                'descripcion' => 'Análisis del pensamiento ético y educativo de Eugenio María de Hostos, enfocado en la justicia social.',
                'autor' => 'Eugenio María de Hostos',
                'año' => 1888,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Electra',
                'descripcion' => 'Drama social y filosófico que marcó un hito en el teatro español por su carga ideológica.',
                'autor' => 'Benito Pérez Galdós',
                'año' => 1901,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Mejor Cocinera, Recetas de Cocina',
                'descripcion' => 'Recetario práctico con preparaciones caseras tradicionales del siglo XX.',
                'autor' => 'Calleja',
                'año' => 1912,
                'isbn' => '',
                'categories' => [7],
                'imagen' => '',
            ],
            [
                'titulo' => 'La rana viajera',
                'descripcion' => 'Relatos breves con humor irónico que critican las costumbres extranjeras y la propia sociedad española.',
                'autor' => 'Julio Camba',
                'año' => 1920,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],            
            [
                'titulo' => 'En viaje',
                'descripcion' => 'Crónica personal de viajes por Europa que combina observación social, política y literatura.',
                'autor' => 'Miguel Cané',
                'año' => 1881,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cabos sueltos: Literatura y lingüística',
                'descripcion' => 'Ensayos críticos que entrelazan el análisis literario y lingüístico con claridad académica.',
                'autor' => 'Julio Cejador y Frauca',
                'año' => 1904,
                'isbn' => '',
                'categories' => [8],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Sueños, Volume I',
                'descripcion' => 'Sátira barroca que retrata con ironía la corrupción y los vicios del alma humana.',
                'autor' => 'Francisco de Quevedo',
                'año' => 1627,
                'isbn' => '9788423911813',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Sueños, Volume II',
                'descripcion' => 'Continuación de los sueños que mezcla lo grotesco con lo filosófico en tono mordaz.',
                'autor' => 'Francisco de Quevedo',
                'año' => 1627,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia natural y moral de las Indias (vol 1)',
                'descripcion' => 'Relato etnográfico y naturalista que describe el Nuevo Mundo desde una mirada europea del siglo XVI.',
                'autor' => 'José de Acosta',
                'año' => 1590,
                'isbn' => '9789682313037',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Compendio del viaje del joven Anacarsis a la Grecia (1 de 2)',
                'descripcion' => 'Viaje ficticio que reconstruye con erudición la Grecia clásica desde los ojos de un extranjero.',
                'autor' => 'J.-J. Barthélemy',
                'año' => 1788,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Páginas sevillanas',
                'descripcion' => 'Recopilación de historias y costumbres populares andaluzas con un enfoque cultural e histórico.',
                'autor' => 'Manuel Chaves Rey',
                'año' => 1923,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Música y Músicos Portorriqueños',
                'descripcion' => 'Estudio pionero sobre la tradición musical de Puerto Rico y sus principales exponentes.',
                'autor' => 'Fernando Callejo Ferrer',
                'año' => 1896,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Política Americana',
                'descripcion' => 'Análisis de las dinámicas políticas del continente desde una óptica crítica del siglo XX.',
                'autor' => 'Alejandro Calvo',
                'año' => 1910,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Argentina, Legend and History',
                'descripcion' => 'Visión literaria e histórica de Argentina, combinando datos reales con narración emotiva.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1910,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de Teruel',
                'descripcion' => 'Minuciosa reconstrucción del pasado de la ciudad aragonesa desde sus orígenes.',
                'autor' => 'Cosme Blasco',
                'año' => 1884,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Suma y Narracion de los Incas',
                'descripcion' => 'Relato clave sobre el origen, expansión y cultura del imperio incaico, desde fuentes tempranas.',
                'autor' => 'Juan de Betánzos',
                'año' => 1551,
                'isbn' => '9788490071948',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Compendio del viaje del joven Anacarsis a la Grecia (2 de 2)',
                'descripcion' => 'Final del relato ilustrado que recorre los templos, costumbres y filosofía de la Grecia antigua.',
                'autor' => 'J.-J. Barthélemy',
                'año' => 1788,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia natural y moral de las Indias (vol 2)',
                'descripcion' => 'Segunda parte del tratado que profundiza en costumbres indígenas y la geografía americana.',
                'autor' => 'José de Acosta',
                'año' => 1590,
                'isbn' => '9789682313044',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Reseña Veridica de la Revolución Filipina',
                'descripcion' => 'Testimonio directo sobre la independencia filipina desde la perspectiva de su principal líder.',
                'autor' => 'Emilio Aguinaldo',
                'año' => 1899,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Viajes por España',
                'descripcion' => 'Impresiones de viaje con estilo literario que capturan el espíritu de diversas regiones españolas.',
                'autor' => 'Pedro Antonio de Alarcón',
                'año' => 1874,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Recuerdos de Italia (parte 1 de 2)',
                'descripcion' => 'Relato de viaje por Italia con tono lírico y análisis cultural de sus ciudades y gentes.',
                'autor' => 'Emilio Castelar',
                'año' => 1872,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Recuerdos de Italia (parte 2 de 2)',
                'descripcion' => 'Segunda parte de la crónica viajera, con énfasis en el arte y la historia del país italiano.',
                'autor' => 'Emilio Castelar',
                'año' => 1872,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Gibaro',
                'descripcion' => 'Costumbrismo puertorriqueño que describe con viveza las tradiciones rurales y populares.',
                'autor' => 'Manuel A. Alonso',
                'año' => 1845,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de los Judíos en España',
                'descripcion' => 'Estudio histórico que analiza la presencia judía en la península ibérica desde la antigüedad.',
                'autor' => 'Adolfo de Castro',
                'año' => 1851,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],            
            [
                'titulo' => 'La transformación de las razas en América',
                'descripcion' => 'Estudio racial y social sobre los cambios étnicos en el continente americano.',
                'autor' => 'Agustín Alvarez',
                'año' => 1911,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'De Las Islas Filipinas',
                'descripcion' => 'Ensayo histórico que describe la situación política y social de Filipinas en el siglo XIX.',
                'autor' => 'Luis Prudencio Alvarez y Tejero',
                'año' => 1887,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Fundación de la ciudad de Buenos-Aires',
                'descripcion' => 'Narración histórica sobre los orígenes y primeras expediciones en la fundación de Buenos Aires.',
                'autor' => 'Pedro de Angelis',
                'año' => 1836,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'España y los Estados Unidos de Norte América : a propósito de la guerra',
                'descripcion' => 'Análisis crítico de la guerra hispano-estadounidense y sus implicaciones para España.',
                'autor' => 'Agustín Aragón',
                'año' => 1898,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La voz de España contra todos sus enemigos',
                'descripcion' => 'Reflexión patriótica y política en defensa de la soberanía española ante amenazas extranjeras.',
                'autor' => 'José María Avilés',
                'año' => 1899,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Biblia en España, Tomo I',
                'descripcion' => 'Relato de viajes y experiencias de un protestante británico en la España del siglo XIX.',
                'autor' => 'George Borrow',
                'año' => 1843,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Biblia en España, Tomo II',
                'descripcion' => 'Continuación del viaje religioso y cultural de George Borrow en tierras españolas.',
                'autor' => 'George Borrow',
                'año' => 1843,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Biblia en España, Tomo III',
                'descripcion' => 'Cierre del testimonio del autor inglés sobre la España profunda del siglo XIX.',
                'autor' => 'George Borrow',
                'año' => 1843,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Protestantismo comparado con el Catolicismo en sus relaciones con la Civilización Europea',
                'descripcion' => 'Comparación filosófica y teológica entre las dos grandes corrientes cristianas de Europa.',
                'autor' => 'Jaime Luciano Balmes',
                'año' => 1842,
                'isbn' => '9788499533350',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Con la Pluma y con el Sable: Crónica de 1820 a 1823',
                'descripcion' => 'Relato histórico de las luchas políticas y militares en España en los años veinte del siglo XIX.',
                'autor' => 'Pío Baroja',
                'año' => 1943,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Indios, su Historia y su Civilización',
                'descripcion' => 'Estudio amplio sobre las culturas indígenas americanas y sus aportes a la civilización.',
                'autor' => 'Antonio Batres Jáuregui',
                'año' => 1894,
                'isbn' => '',
               'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Salambó',
                'descripcion' => 'Novela histórica ambientada en Cartago que mezcla sensualidad, religión y guerra.',
                'autor' => 'Gustave Flaubert',
                'año' => 1862,
                'isbn' => '9788497407912',
                'categories' => [1, 13],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de Venezuela, Tomo I',
                'descripcion' => 'Relato colonial sobre la formación política y social del territorio venezolano.',
                'autor' => 'Pedro de Aguado',
                'año' => 1581,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de Venezuela, Tomo II',
                'descripcion' => 'Segunda parte del extenso relato de la colonización y desarrollo de Venezuela.',
                'autor' => 'Pedro de Aguado',
                'año' => 1581,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Lo que dice la historia',
                'descripcion' => 'Crónica breve que destaca episodios relevantes del pasado hispanoamericano.',
                'autor' => 'Salvador Brau',
                'año' => 1893,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de la decadencia de España',
                'descripcion' => 'Análisis político y económico del declive de la hegemonía española.',
                'autor' => 'Antonio Cánovas del Castillo',
                'año' => 1885,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Guerra de razas (Negros contra Blancos en Cuba)',
                'descripcion' => 'Estudio de uno de los conflictos raciales más intensos de la historia cubana.',
                'autor' => 'Rafael Conte',
                'año' => 1912,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Política de los Estados Unidos en el Continente Americano',
                'descripcion' => 'Crítica sobre la expansión y estrategias geopolíticas de EE. UU. en América Latina.',
                'autor' => 'Raúl de Cárdenas',
                'año' => 1925,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de las Indias (vol. 1 de 5)',
                'descripcion' => 'Testimonio crucial de la colonización americana desde la perspectiva de un defensor indígena.',
                'autor' => 'Bartolomé de las Casas',
                'año' => 1552,
                'isbn' => '9788490071967',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de las Indias (vol. 2 de 5)',
                'descripcion' => 'Continuación del alegato histórico y moral contra los abusos cometidos en América.',
                'autor' => 'Bartolomé de las Casas',
                'año' => 1552,
                'isbn' => '9788490071967',
                'categories' => [4],
                'imagen' => '',
            ],            
            [
                'titulo' => 'Historia de las Indias (vol. 3 de 5)',
                'descripcion' => 'Profundo análisis de la conquista desde la perspectiva crítica de un fraile defensor de los indígenas.',
                'autor' => 'Bartolomé de las Casas',
                'año' => 1552,
                'isbn' => '9788490071967',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de las Indias (vol. 4 de 5)',
                'descripcion' => 'Relato continuo de las injusticias cometidas en América, con documentación histórica clave.',
                'autor' => 'Bartolomé de las Casas',
                'año' => 1552,
                'isbn' => '9788490071967',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de las Indias (vol. 5 de 5)',
                'descripcion' => 'Cierre del influyente testimonio que denuncia los abusos coloniales en América.',
                'autor' => 'Bartolomé de las Casas',
                'año' => 1552,
                'isbn' => '9788490071967',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de la lengua y literatura castellana, Tomo 1: Desde los orígenes hasta Carlos V',
                'descripcion' => 'Panorama detallado de la evolución del idioma y la literatura española desde sus inicios.',
                'autor' => 'Julio Cejador y Frauca',
                'año' => 1905,
                'isbn' => '',
                'categories' => [8],
                'imagen' => '',
            ],
            [
                'titulo' => 'Historia de la lengua y literatura castellana, Tomo 2: Época de Carlos V',
                'descripcion' => 'Exploración de la literatura y el lenguaje en tiempos del Renacimiento español.',
                'autor' => 'Julio Cejador y Frauca',
                'año' => 1905,
                'isbn' => '',
                'categories' => [8],
                'imagen' => '',
            ],
            [
                'titulo' => 'Místicas',
                'descripcion' => 'Obra poética contemporánea que combina espiritualidad y reflexión profunda.',
                'autor' => 'María Raquel Adler',
                'año' => 1998,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Eneida; v.1 de 2',
                'descripcion' => 'Primera parte del clásico épico romano que narra el origen mítico de Roma.',
                'autor' => 'Virgil',
                'año' => -19,
                'isbn' => '9788467025095',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Eneida; v.2 de 2',
                'descripcion' => 'Conclusión del poema épico que glorifica la figura de Eneas y la grandeza romana.',
                'autor' => 'Virgil',
                'año' => -19,
                'isbn' => '9788467025095',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La verbena de la Paloma',
                'descripcion' => 'Zarzuela clásica española que retrata con humor los celos y las costumbres populares.',
                'autor' => 'Ricardo de la Vega',
                'año' => 1894,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Nuevas poesías y evangélicas',
                'descripcion' => 'Versos combativos y espirituales de uno de los poetas sociales más influyentes de Argentina.',
                'autor' => 'Almafuerte',
                'año' => 1917,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Obras escogidas',
                'descripcion' => 'Selección de poemas y leyendas de Bécquer, figura esencial del romanticismo español.',
                'autor' => 'Gustavo Adolfo Bécquer',
                'año' => 1871,
                'isbn' => '9788420652016',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Argentina, o La conquista del Rio de La Plata',
                'descripcion' => 'Poema épico sobre la exploración y conquista del Río de la Plata en el siglo XVI.',
                'autor' => 'Martín del Barco Centenera',
                'año' => 1602,
                'isbn' => '',
                'categories' => [4],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Divina Comedia',
                'descripcion' => 'Viaje alegórico por el Infierno, el Purgatorio y el Paraíso en una obra maestra de la literatura universal.',
                'autor' => 'Dante Alighieri',
                'año' => 1321,
                'isbn' => '9788420652146',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Orlando Furioso, Tomo I',
                'descripcion' => 'Primera parte del poema épico que combina caballería, magia y amor en el Renacimiento italiano.',
                'autor' => 'Lodovico Ariosto',
                'año' => 1532,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Orlando Furioso, Tomo II',
                'descripcion' => 'Cierre de la epopeya italiana donde se entrelazan aventuras y pasiones en un mundo fantástico.',
                'autor' => 'Lodovico Ariosto',
                'año' => 1532,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Quince minutos en globo',
                'descripcion' => 'Relato corto con toques de fantasía que retrata un viaje insólito y reflexivo.',
                'autor' => 'Joaquín Barberá',
                'año' => 1925,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Malquerida : Drama en tres actos y en prosa',
                'descripcion' => 'Tragedia rural que expone los conflictos familiares y la represión en un ambiente cerrado.',
                'autor' => 'Jacinto Benavente',
                'año' => 1913,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Señora ama: Comedia en tres actos',
                'descripcion' => 'Comedia dramática sobre los celos, el amor y el papel de la mujer en el hogar tradicional.',
                'autor' => 'Jacinto Benavente',
                'año' => 1908,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los Lusíadas: Poema épico en diez cantos',
                'descripcion' => 'Poema nacional de Portugal que narra los viajes de Vasco da Gama y la grandeza lusa.',
                'autor' => 'Luís de Camões',
                'año' => 1572,
                'isbn' => '9788437603042',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Impresiones, Poesías',
                'descripcion' => 'Recopilación de versos líricos que exploran el sentimiento, la patria y la contemplación.',
                'autor' => 'José Campo-Arana',
                'año' => 1932,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],            
            [
                'titulo' => 'Juvenilla',
                'descripcion' => 'Relato autobiográfico que retrata la vida estudiantil y política en el Buenos Aires del siglo XIX.',
                'autor' => 'Miguel Cané',
                'año' => 1884,
                'isbn' => '9789500729012',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'En las orillas del Sar',
                'descripcion' => 'Poemario íntimo y melancólico que refleja el sentir gallego y el alma femenina.',
                'autor' => 'Rosalía de Castro',
                'año' => 1884,
                'isbn' => '9788475178946',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Clásicos Castellanos: Libro de Buen Amor',
                'descripcion' => 'Obra maestra del mester de clerecía, mezcla de humor, crítica social y alegoría amorosa.',
                'autor' => 'Juan Ruiz',
                'año' => 1330,
                'isbn' => '9788424922047',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Viage al Parnaso',
                'descripcion' => 'Sátira poética en la que Cervantes defiende el arte verdadero frente a la mediocridad literaria.',
                'autor' => 'Miguel de Cervantes Saavedra',
                'año' => 1614,
                'isbn' => '',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Ilíada',
                'descripcion' => 'Poema épico que narra la guerra de Troya, la cólera de Aquiles y el destino de los héroes.',
                'autor' => 'Homero',
                'año' => -750,
                'isbn' => '9788420637884',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'La Odisea',
                'descripcion' => 'Epopeya clásica que sigue las aventuras de Ulises en su regreso a Ítaca tras la guerra de Troya.',
                'autor' => 'Homero',
                'año' => -700,
                'isbn' => '9788420637914',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Fabulas de Esopo',
                'descripcion' => 'Colección de relatos breves con moraleja que transmiten sabiduría popular universal.',
                'autor' => 'Esopo',
                'año' => -550,
                'isbn' => '9788426102614',
                'categories' => [5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Metamorfóseos o Transformaciones (1 de 4)',
                'descripcion' => 'Inicio de la obra mitológica que relata las transformaciones legendarias del mundo grecorromano.',
                'autor' => 'Ovid',
                'año' => 8,
                'isbn' => '9788437625587',
                'categories' => [5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Metamorfóseos o Transformaciones (2 de 4)',
                'descripcion' => 'Continuación de los mitos clásicos que exploran la relación entre dioses y humanos.',
                'autor' => 'Ovid',
                'año' => 8,
                'isbn' => '9788437625587',
                'categories' => [5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Metamorfóseos o Transformaciones (3 de 4)',
                'descripcion' => 'Relatos poéticos donde el cambio físico representa dramas espirituales y pasionales.',
                'autor' => 'Ovid',
                'año' => 8,
                'isbn' => '9788437625587',
                'categories' => [5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Metamorfóseos o Transformaciones (4 de 4)',
                'descripcion' => 'Cierre de la obra que narra las más famosas transformaciones míticas de la antigüedad.',
                'autor' => 'Ovid',
                'año' => 8,
                'isbn' => '9788437625587',
                'categories' => [5],
                'imagen' => '',
            ],
            [
                'titulo' => 'Tragedias',
                'descripcion' => 'Dramas clásicos que abordan el destino, la justicia divina y la moral en la antigua Grecia.',
                'autor' => 'Aeschylus',
                'año' => -458,
                'isbn' => '9788437601888',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Thespis (novelas cortas y cuentos)',
                'descripcion' => 'Recopilación de relatos breves que mezclan crítica social y estilo filosófico.',
                'autor' => 'Carlos O. Bunge',
                'año' => 1893,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'Doctor Sutilis',
                'descripcion' => 'Narraciones psicológicas con un tono irónico que revelan la complejidad del alma humana.',
                'autor' => 'Leopoldo Alas',
                'año' => 1895,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'El Señor y los demás son Cuentos',
                'descripcion' => 'Colección de cuentos realistas con sensibilidad social y profundidad psicológica.',
                'autor' => 'Leopoldo Alas',
                'año' => 1892,
                'isbn' => '9788420609294',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cuentos de Fray Mocho',
                'descripcion' => 'Historias humorísticas y costumbristas del Buenos Aires de fines del siglo XIX.',
                'autor' => 'José S. Alvarez',
                'año' => 1894,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'La voz de la conseja',
                'descripcion' => 'Cuentos breves con sabor andaluz que mezclan tradición oral y gracia popular.',
                'autor' => 'Joaquín Álvarez Quintero',
                'año' => 1915,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los espectros',
                'descripcion' => 'Relato sombrío que examina la culpa, la locura y la muerte con una atmósfera inquietante.',
                'autor' => 'Leonid Andreyev',
                'año' => 1908,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cuentos escogidos',
                'descripcion' => 'Selección de relatos breves que reflejan lo mejor del estilo agudo y realista de Maupassant.',
                'autor' => 'Guy de Maupassant',
                'año' => 1884,
                'isbn' => '9788420622729',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cuentos de poeta',
                'descripcion' => 'Relatos con carga lírica y visión crítica del mundo hispanoamericano.',
                'autor' => 'Rufino Blanco-Fombona',
                'año' => 1900,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],            
            [
                'titulo' => 'La condenada',
                'descripcion' => 'Relato breve que combina drama y crítica social con la intensidad característica del autor.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1895,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cuentos valencianos',
                'descripcion' => 'Colección de relatos ambientados en la huerta valenciana, con personajes entrañables y vívidos.',
                'autor' => 'Vicente Blasco Ibáñez',
                'año' => 1896,
                'isbn' => '9788435018138',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cuentos Clásicos del Norte, Primera Serie',
                'descripcion' => 'Relatos oscuros y misteriosos del maestro del terror psicológico y lo sobrenatural.',
                'autor' => 'Edgar Allan Poe',
                'año' => 1845,
                'isbn' => '9788490743864',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Cuentos Clásicos del Norte, Segunda Serie',
                'descripcion' => 'Narraciones de tono romántico y fantástico que evocan el espíritu de la América colonial.',
                'autor' => 'Washington Irving',
                'año' => 1820,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Tres relatos porteños',
                'descripcion' => 'Tres cuentos ambientados en Buenos Aires que combinan humor, crítica y picardía.',
                'autor' => 'Arturo Cancela',
                'año' => 1922,
                'isbn' => '',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Los entremeses',
                'descripcion' => 'Breves piezas teatrales de tono satírico que muestran la vida popular del Siglo de Oro español.',
                'autor' => 'Miguel de Cervantes Saavedra',
                'año' => 1615,
                'isbn' => '9788437601826',
                'categories' => [3],
                'imagen' => '',
            ],
            [
                'titulo' => 'Novelas ejemplares',
                'descripcion' => 'Doce relatos con enseñanzas morales y gran diversidad de estilos y temáticas.',
                'autor' => 'Miguel de Cervantes Saavedra',
                'año' => 1613,
                'isbn' => '9788420626468',
                'categories'=> [2],
                'imagen' => '',
            ],
            [
                'titulo' => 'Novelas y teatro',
                'descripcion' => 'Compilación de obras que destaca la versatilidad literaria de Cervantes más allá del Quijote.',
                'autor' => 'Miguel de Cervantes Saavedra',
                'año' => 1613,
                'isbn' => '',
                'categories' => [6],
                'imagen' => '',
            ],
            [
                'titulo' => 'Memorias de un vigilante',
                'descripcion' => 'Autobiografía que ofrece una visión crítica y humorística de la vida urbana en Argentina.',
                'autor' => 'José S. Alvarez',
                'año' => 1897,
                'isbn' => '',
                'categories' => [14],
                'imagen' => '',
            ],
            [
                'titulo' => 'Poetas de color',
                'descripcion' => 'Retratos y semblanzas de autores afrodescendientes que reivindican su lugar en la literatura.',
                'autor' => 'Francisco Calcagno',
                'año' => 1894,
                'isbn' => '',
                'categories' => [14],
                'imagen' => '',
            ],
            [
                'titulo' => 'Biografia del libertador Simón Bolívar',
                'descripcion' => 'Perfil patriótico del prócer venezolano, destacando sus ideales y campañas libertadoras.',
                'autor' => 'Lorenzo Campano',
                'año' => 1883,
                'isbn' => '',
                'categories' => [14],
                'imagen' => '',
            ],
                       
        ];

        foreach ($libros as $libro) {
            $book = Book::firstOrCreate(
                ['titulo' => $libro['titulo'], 'autor' => $libro['autor']],
                [
                    'descripcion' => $libro['descripcion'],
                    'año' => $libro['año'],
                    'isbn' => $libro['isbn'],
                    'imagen' => $libro['imagen'],
                ]
            );
        
            if (!empty($libro['categories'])) {
                $book->categories()->syncWithoutDetaching($libro['categories']);
            }
        }
        
    }
}
